FROM golang:1.24.2-alpine AS base
WORKDIR /app

ENV GO111MODULE="on"
ENV GOOS="linux"
ENV CGO_ENABLED=0

RUN apk update \
    && apk add --no-cache \
    ca-certificates \
    git \
    && update-ca-certificates \
    && go install github.com/air-verse/air@latest \
    && go install github.com/go-delve/delve/cmd/dlv@latest
    
EXPOSE 8080
EXPOSE 2345

ENTRYPOINT ["air"]