version: "3"

services:
  connect:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=dev
    ports:
      - 8080:8080
    volumes:
      - .:/app:rw,delegated
      - ./cmd/connect/.air.toml:/app/.air.toml
    networks:
      - home-plan-network
    depends_on:
      - db
  optimiser:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=dev
      - PUBSUB_EMULATOR_HOST=host.docker.internal:8085
    ports:
      - 8081:8080
      - 2345:2345
    volumes:
      - .:/app:rw,delegated
      - ./cmd/optimiser/.air.toml:/app/.air.toml
    networks:
      - home-plan-network
    depends_on:
      - db
  db:
    image: "postgres:16.2-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "dev"
    restart: always
    networks:
      - home-plan-network
    ports:
      - 5432:5432
      - 2346:2345
networks:
  home-plan-network: