version: "3"

services:
  connect:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=connect
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - .:/app:rw,delegated
      - ./cmd/connect/.air.toml:/app/.air.toml
    networks:
      - home-plan-network
    depends_on:
      - connect-db
  weather:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PORT=5433
      - DB_PASSWORD=postgres
      - DB_NAME=weather
    ports:
      - 8082:8080
      - 2347:2345
    volumes:
      - .:/app:rw,delegated
      - ./cmd/weather/.air.toml:/app/.air.toml
    networks:
      - home-plan-network
    depends_on:
      - weather-db
  optimiser:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PORT=5434
      - DB_PASSWORD=postgres
      - DB_NAME=optimiser
      - PUBSUB_EMULATOR_HOST=host.docker.internal:8085
    ports:
      - 8081:8080
      - 2346:2345
    volumes:
      - .:/app:rw,delegated
      - ./cmd/optimiser/.air.toml:/app/.air.toml
    networks:
      - home-plan-network
    depends_on:
      - optimiser-db
  grid:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=postgres
      - DB_PORT=5435
      - DB_PASSWORD=postgres
      - DB_NAME=grid
    ports:
      - 8083:8080
      - 2348:2345
    volumes:
      - .:/app:rw,delegated
      - ./cmd/grid/.air.toml:/app/.air.toml
    networks:
      - home-plan-network
    depends_on:
      - grid-db
  connect-db:
    volumes:
      - connect-db-data:/var/lib/postgresql/data
    image: "postgres:16.2-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "connect"
    restart: always
    networks:
      - home-plan-network
    ports:
      - 5432:5432
  weather-db:
    volumes:
      - weather-db-data:/var/lib/postgresql/data
    image: "postgres:16.2-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "weather"
    restart: always
    networks:
      - home-plan-network
    ports:
      - 5433:5432
  optimiser-db:
    volumes:
      - optimiser-db-data:/var/lib/postgresql/data
    image: "postgres:16.2-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "optimiser"
    restart: always
    networks:
      - home-plan-network
    ports:
      - 5434:5432
  grid-db:
    volumes:
      - grid-db-data:/var/lib/postgresql/data
    image: "postgres:16.2-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "grid"
    restart: always
    networks:
      - home-plan-network
    ports:
      - 5435:5432
networks:
  home-plan-network:
volumes:
  connect-db-data:
  weather-db-data:
  optimiser-db-data:
  grid-db-data: