root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./app github.com/jackthomsonn/home-plan/cmd/connect"
bin = "./app"
full_bin = "dlv exec --accept-multiclient --log --headless --continue --listen :2345 --api-version 2 ./app"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["scripts"]